version: "3.5"
services:
    tom_calculator_backend:
        container_name: tom_calculator_backend
        restart: always
        build:
            context: ./
            dockerfile: docker/backend/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend/:/app/
        environment:
            PYTHONPATH: /app
            PYTHONBUFFERED: 1
            TOML_CONFIG_PATH: config.toml

    tom_calculator_frontend:
        build:
            context: ./
            dockerfile: docker/frontend/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - tom_calculator_backend
        environment:
            BACKEND_URL: http://tom_calculator_backend:8000